import { motion } from "framer-motion";
import { BriefcaseBusiness, Building2, Edit3, Landmark, PieChart as PieChartIcon, PiggyBank, Plus, Search, Trash2, TrendingUp, Wallet } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { EmptyChart, MiniMetric, ProgressBar } from "@/components/common";
import { categoryLabels } from "@/constants";
import { clampNumber, currency } from "@/utils/format";
import { getFundHoldingsCount, getFundPortfolioValue, isPortfolioFund, monthsToTarget } from "@/utils/portfolio";

const fundIcons = { brokerage: TrendingUp, roth: Landmark, savings: PiggyBank, realEstate: Building2, business: BriefcaseBusiness, custom: Wallet };

export function DashboardView({ funds, allEtfs, query, setQuery, categoryFilter, setCategoryFilter, setEditingFund, deleteFund, quickContribution, openPortfolioForFund }) {
  return <section className="mt-6"><Card className="rounded-[2rem] border-white/10 bg-white/[0.04] text-slate-100 shadow-xl backdrop-blur"><CardHeader className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><CardTitle className="text-xl">Your Funds</CardTitle><p className="mt-1 text-sm text-slate-400">Brokerage and Roth funds can open into their own ETF portfolio.</p></div><div className="flex flex-col gap-3 sm:flex-row"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search funds..." className="h-11 rounded-2xl border-white/10 bg-slate-950/60 pl-9 text-slate-100 placeholder:text-slate-500" /></div><Select value={categoryFilter} onValueChange={setCategoryFilter}><SelectTrigger className="h-11 w-full rounded-2xl border-white/10 bg-slate-950/60 text-slate-100 sm:w-48"><SelectValue /></SelectTrigger><SelectContent className="border-white/10 bg-slate-950 text-slate-100"><SelectItem value="all">All categories</SelectItem>{Object.entries(categoryLabels).map(([key, label]) => <SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select></div></CardHeader><CardContent><div className="grid gap-4">{funds.map((fund, index) => <FundCard key={fund.id} fund={fund} allEtfs={allEtfs} index={index} onEdit={() => setEditingFund(fund)} onDelete={() => deleteFund(fund.id)} onQuickContribution={() => quickContribution(fund)} onOpenPortfolio={() => openPortfolioForFund(fund.id)} />)}{funds.length === 0 && <EmptyChart text="No funds match your search." />}</div></CardContent></Card></section>;
}

function FundCard({ fund, allEtfs, index, onEdit, onDelete, onQuickContribution, onOpenPortfolio }) {
  const Icon = fundIcons[fund.category] || Wallet;
  const progress = fund.target > 0 ? (fund.current / fund.target) * 100 : 0;
  const months = monthsToTarget(fund);
  const canHavePortfolio = isPortfolioFund(fund);
  const holdingsCount = getFundHoldingsCount(fund.id, allEtfs);
  const portfolioValue = getFundPortfolioValue(fund.id, allEtfs);
  return <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35, delay: index * 0.03 }} className="rounded-3xl border border-white/10 bg-slate-950/45 p-4 shadow-lg"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-400/20 to-sky-400/20 text-emerald-200"><Icon className="h-6 w-6" /></div><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-semibold">{fund.name}</h3><span className="rounded-full border border-white/10 bg-white/5 px-2.5 py-1 text-xs text-slate-300">{categoryLabels[fund.category] || "Custom Fund"}</span>{canHavePortfolio && <span className="rounded-full border border-sky-400/20 bg-sky-400/10 px-2.5 py-1 text-xs text-sky-300">{holdingsCount > 0 ? `${holdingsCount} holdings` : "Portfolio not set up"}</span>}</div><p className="mt-1 max-w-2xl text-sm text-slate-400">{fund.notes || "No notes added yet."}</p></div></div><div className="flex shrink-0 flex-wrap gap-2">{canHavePortfolio && <Button size="sm" onClick={onOpenPortfolio} className="rounded-xl bg-sky-400 text-slate-950 hover:bg-sky-300"><PieChartIcon className="mr-1.5 h-4 w-4" />{holdingsCount > 0 ? "View Portfolio" : "Set Up Portfolio"}</Button>}<Button size="sm" onClick={onQuickContribution} className="rounded-xl bg-emerald-400 text-slate-950 hover:bg-emerald-300"><Plus className="mr-1.5 h-4 w-4" />Add Monthly</Button><Button size="sm" variant="outline" onClick={onEdit} className="rounded-xl border-white/10 bg-white/5 text-slate-100 hover:bg-white/10"><Edit3 className="h-4 w-4" /></Button><Button size="sm" variant="outline" onClick={onDelete} className="rounded-xl border-red-400/20 bg-red-400/10 text-red-200 hover:bg-red-400/20"><Trash2 className="h-4 w-4" /></Button></div></div><div className="mt-5 grid gap-3 md:grid-cols-5"><MiniMetric label="Current" value={currency(fund.current)} /><MiniMetric label="Target" value={currency(fund.target)} /><MiniMetric label="Monthly" value={currency(fund.monthlyContribution)} /><MiniMetric label="Annual return" value={`${clampNumber(fund.annualReturn).toFixed(1)}%`} /><MiniMetric label="ETA" value={months === Infinity ? "No plan" : months === 0 ? "Done" : `${months} mo`} /></div>{canHavePortfolio && <div className="mt-3 rounded-2xl border border-sky-400/20 bg-sky-400/10 p-3 text-sm text-sky-100"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between"><span>Portfolio value: <b>{portfolioValue > 0 ? currency(portfolioValue) : "Not set up"}</b></span><span className="text-sky-100/70">This value rolls into total assets and net worth.</span></div></div>}<ProgressBar progress={progress} /></motion.div>;
}
