import { TrendingUpIcon } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { ChartCard } from "@/components/common";
import { MultiLineViz } from "@/components/charts";
import { currency } from "@/utils/format";

export function ProjectionView({ projectionData, milestoneData, settings, funds, setData }) {
  const updateFundReturn = (id, value) => setData((prev) => ({ ...prev, funds: prev.funds.map((fund) => (fund.id === id ? { ...fund, annualReturn: value } : fund)) }));
  return <section className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_0.9fr]"><ChartCard title="Growth Projection" subtitle="Projected assets, debt, and net worth using annual return assumptions."><div className="mb-4 grid gap-3 sm:grid-cols-2"><div><Label>Projection years</Label><Input type="number" value={settings.projectionYears} onChange={(e) => setData((prev) => ({ ...prev, settings: { ...prev.settings, projectionYears: e.target.value } }))} className="mt-2 rounded-2xl border-white/10 bg-slate-900 text-slate-100" /></div><div className="rounded-2xl border border-white/10 bg-slate-950/50 p-3 text-sm text-slate-300">Debt lowers projected net worth until balances are paid off.</div></div><MultiLineViz data={projectionData} funds={funds} /></ChartCard><Card className="rounded-[2rem] border-white/10 bg-white/[0.04] text-slate-100 shadow-xl backdrop-blur"><CardHeader><CardTitle>Return Assumptions</CardTitle><p className="text-sm text-slate-400">Edit expected annual return by fund.</p></CardHeader><CardContent><div className="grid gap-3">{funds.map((fund) => <div key={fund.id} className="rounded-2xl border border-white/10 bg-slate-950/50 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{fund.name}</p><p className="text-sm text-slate-400">Current: {currency(fund.current)} / Monthly: {currency(fund.monthlyContribution)}</p></div><div className="w-full sm:w-36"><Label className="text-xs text-slate-400">Annual return %</Label><Input type="number" value={fund.annualReturn} onChange={(e) => updateFundReturn(fund.id, e.target.value)} className="mt-1 rounded-2xl border-white/10 bg-slate-900 text-slate-100" /></div></div></div>)}</div></CardContent></Card><Card className="rounded-[2rem] border-white/10 bg-white/[0.04] text-slate-100 shadow-xl backdrop-blur xl:col-span-2"><CardHeader><CardTitle>Net Worth Milestone Forecast</CardTitle><p className="text-sm text-slate-400">Estimated time to major milestones using assets minus debt.</p></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{milestoneData.map((m) => <div key={m.target} className="flex items-center justify-between rounded-2xl border border-white/10 bg-slate-950/50 p-4"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-400/10 p-2"><TrendingUpIcon className="h-4 w-4 text-emerald-300" /></div><span>{currency(m.target)}</span></div><span className="font-semibold text-emerald-300">{m.months === Infinity ? "600+ mo" : m.months === 0 ? "Reached" : `${m.months} mo`}</span></div>)}</div></CardContent></Card></section>;
}
