import { Download, RefreshCcw, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { MiniMetric } from "@/components/common";
import { IRA_ANNUAL_LIMIT, IRA_LIMIT_YEAR, STORAGE_KEY } from "@/constants";

export function SettingsView({ settings, setData, resetAll, exportData }) {
  return <section className="mt-6 grid gap-6 lg:grid-cols-2"><Card className="rounded-[2rem] border-white/10 bg-white/[0.04] text-slate-100 shadow-xl backdrop-blur"><CardHeader><CardTitle>Settings</CardTitle><p className="text-sm text-slate-400">API keys are stored locally in this browser only.</p></CardHeader><CardContent className="grid gap-4"><div><Label>Finnhub API key</Label><Input type="password" value={settings.finnhubApiKey || ""} onChange={(e) => setData((prev) => ({ ...prev, settings: { ...prev.settings, finnhubApiKey: e.target.value } }))} placeholder="Paste Finnhub API key here" className="mt-2 rounded-2xl border-white/10 bg-slate-900 text-slate-100" /></div><div><Label>Backup reminder frequency in days</Label><Input type="number" value={settings.backupFrequencyDays} onChange={(e) => setData((prev) => ({ ...prev, settings: { ...prev.settings, backupFrequencyDays: e.target.value } }))} className="mt-2 rounded-2xl border-white/10 bg-slate-900 text-slate-100" /></div><div className="rounded-2xl border border-white/10 bg-slate-950/50 p-4"><Label className="flex items-center gap-3"><input type="checkbox" checked={Boolean(settings.projectIraLimitGrowth)} onChange={(e) => setData((prev) => ({ ...prev, settings: { ...prev.settings, projectIraLimitGrowth: e.target.checked } }))} />Grow IRA max in projections</Label><p className="mt-2 text-sm text-slate-400">Starts from the {IRA_LIMIT_YEAR} ${IRA_ANNUAL_LIMIT.toLocaleString()} standard limit and grows it by the inflation rate.</p></div><MiniMetric label="Last backup" value={settings.lastBackupDate || "Never"} /><Button onClick={exportData} className="rounded-2xl bg-emerald-400 text-slate-950 hover:bg-emerald-300"><Download className="mr-2 h-4 w-4" />Export JSON Backup</Button></CardContent></Card><Card className="rounded-[2rem] border-white/10 bg-white/[0.04] text-slate-100 shadow-xl backdrop-blur"><CardHeader><CardTitle>Local Data Controls</CardTitle><p className="text-sm text-slate-400">Useful while developing locally.</p></CardHeader><CardContent className="flex flex-wrap gap-3"><Button variant="outline" onClick={resetAll} className="rounded-2xl border-white/10 bg-white/5 text-slate-100 hover:bg-white/10"><RefreshCcw className="mr-2 h-4 w-4" />Reset Starter Template</Button><Button variant="outline" onClick={() => localStorage.removeItem(STORAGE_KEY)} className="rounded-2xl border-red-400/20 bg-red-400/10 text-red-200 hover:bg-red-400/20"><Trash2 className="mr-2 h-4 w-4" />Clear Local Save Only</Button></CardContent></Card></section>;
}
